# Generated by Django 3.2.6 on 2022-01-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('address', models.TextField()),
                ('county', models.TextField()),
                ('state', models.TextField()),
                ('numsVaccinesRequired', models.BigIntegerField()),
                ('recentTestRequired', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phoneNumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-name', '-phoneNumber', '-email', '-vaccinationNum', '-recentTestNegative']},
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phoneNumber',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='recentTestNegative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='vaccinationNum',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
