# Generated by Django 3.2.6 on 2022-01-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20220116_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-name', '-description', '-date', '-address', '-county', '-state', '-numVaccinesRequired', '-recentTestRequired']},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['-name', '-phoneNumber', '-email']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='numsVaccinesRequired',
            new_name='numVaccinesRequired',
        ),
    ]
