# Generated by Django 3.2.6 on 2022-01-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20220116_0315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-name', '-description', '-date', '-address', '-county', '-state', '-numVaccinesRequired', '-recentTestRequired', '-hostName', '-hostEmail', '-hostPhoneNumber']},
        ),
        migrations.AddField(
            model_name='event',
            name='hostEmail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='hostName',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='hostPhoneNumber',
            field=models.BigIntegerField(default='555555555'),
            preserve_default=False,
        ),
    ]
