# Generated by Django 3.2.6 on 2022-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_auto_20220116_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phoneNumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
