# Generated by Django 3.2.6 on 2022-01-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0007_auto_20220116_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-name', '-description', '-date', '-address', '-county', '-state', '-numVaccinesRequired', '-recentTestRequired', '-hostName', '-hostEmail', '-hostPhoneNumber', '-eventCode']},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-name', '-phoneNumber', '-email', '-vaccinationNum', '-recentTestNegative', '-eventID']},
        ),
        migrations.AddField(
            model_name='event',
            name='eventCode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='eventID',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
