# Generated by Django 3.2.6 on 2022-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0008_auto_20220116_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
    ]
