# Generated by Django 3.2.6 on 2022-01-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0009_eventfinder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFinder',
        ),
    ]
